name: Build container for ASAM Project Guide 

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs: 
  docker-build:
    name: Prepare the ASAM project guide by cloning and running pre-build scripts
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha

    - name: debug meta data step
      run: |
        ls -la 
        echo ${{ steps.meta.outputs.tags }}
        echo ${{ steps.meta.outputs.labels }}


    # - name: Build and push
    #   id: docker_build
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: |
    #       ghcr.io/user/app:latest
    #       ghcr.io/user/app:1.0.0


# echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
# docker push ghcr.io/OWNER/IMAGE_NAME:latest